"""channel integrations

Revision ID: 6a953cd13cf6
Revises: d5f2a83c61be
Create Date: 2026-09-08 18:28:37.580261

Four new tables and nothing else. Purely additive: no existing table is
touched, so unlike d5f2a83c61be this one has no half-applied-DDL hazard on
MySQL, and downgrade is a clean drop.

Autogenerate also proposed re-creating the `use_alter` audit foreign keys on
six existing tables and clearing a server default on `condos`. Both are
long-standing drift between the models and the live schema, unrelated to
channels, and dropping foreign keys on populated tables to fix a cosmetic diff
is not something a feature migration should do. Removed deliberately; they will
keep appearing in autogenerate until someone addresses them on purpose.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Binds `app` in this namespace so autogenerate's `app.models.base.GUID(...)`
# references resolve. `import ... as x` would bind only `x`.
import app.models.base

revision: str = '6a953cd13cf6'
down_revision: str | None = 'd5f2a83c61be'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel_connections',
    sa.Column('channel', sa.Enum('airbnb', name='channel', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('connected', 'disconnected', 'error', name='connectionstatus', native_enum=False, length=20), nullable=False),
    sa.Column('account_label', sa.String(length=160), nullable=True),
    sa.Column('credentials', app.common.crypto.SecretText(), nullable=True),
    sa.Column('credentials_expires_at', sa.DateTime(), nullable=True),
    sa.Column('connected_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('id', app.models.base.GUID(length=16), nullable=False),
    sa.Column('organisation_id', app.models.base.GUID(length=16), nullable=False),
    sa.Column('created_by', app.models.base.GUID(length=16), nullable=True),
    sa.Column('updated_by', app.models.base.GUID(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_channel_connections_created_by'), ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_channel_connections_organisation_id')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_channel_connections_updated_by'), ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_channel_connections'))
    )
    op.create_index(op.f('ix_channel_connections_organisation_id'), 'channel_connections', ['organisation_id'], unique=False)
    op.create_index('uq_channel_connections_organisation_id_channel', 'channel_connections', ['organisation_id', 'channel'], unique=True)
    op.create_table('channel_listings',
    sa.Column('connection_id', app.models.base.GUID(length=16), nullable=False),
    sa.Column('condo_id', app.models.base.GUID(length=16), nullable=False),
    sa.Column('external_listing_id', sa.String(length=64), nullable=False),
    sa.Column('external_label', sa.String(length=255), nullable=True),
    sa.Column('import_url', app.common.crypto.SecretText(), nullable=True),
    sa.Column('export_token', app.common.crypto.SecretText(), nullable=True),
    sa.Column('export_token_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('active', 'paused', 'error', name='listingstatus', native_enum=False, length=20), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('last_success_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('id', app.models.base.GUID(length=16), nullable=False),
    sa.Column('organisation_id', app.models.base.GUID(length=16), nullable=False),
    sa.Column('created_by', app.models.base.GUID(length=16), nullable=True),
    sa.Column('updated_by', app.models.base.GUID(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['condo_id'], ['condos.id'], name=op.f('fk_channel_listings_condo_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['connection_id'], ['channel_connections.id'], name=op.f('fk_channel_listings_connection_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_channel_listings_created_by'), ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_channel_listings_organisation_id')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_channel_listings_updated_by'), ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_channel_listings'))
    )
    op.create_index('ix_channel_listings_connection_condo', 'channel_listings', ['connection_id', 'condo_id'], unique=False)
    op.create_index('ix_channel_listings_due', 'channel_listings', ['deleted_at', 'status', 'next_attempt_at'], unique=False)
    op.create_index('ix_channel_listings_external', 'channel_listings', ['connection_id', 'external_listing_id'], unique=False)
    op.create_index(op.f('ix_channel_listings_organisation_id'), 'channel_listings', ['organisation_id'], unique=False)
    op.create_index('uq_channel_listings_export_token_hash', 'channel_listings', ['export_token_hash'], unique=True)
    op.create_table('channel_reservations',
    sa.Column('listing_id', app.models.base.GUID(length=16), nullable=False),
    sa.Column('booking_id', app.models.base.GUID(length=16), nullable=True),
    sa.Column('external_reservation_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('active', 'cancelled', name='channelreservationstatus', native_enum=False, length=20), nullable=False),
    sa.Column('check_in', sa.Date(), nullable=False),
    sa.Column('check_out', sa.Date(), nullable=False),
    sa.Column('summary', sa.String(length=255), nullable=True),
    sa.Column('guest_count', sa.Integer(), nullable=True),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('id', app.models.base.GUID(length=16), nullable=False),
    sa.Column('organisation_id', app.models.base.GUID(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_channel_reservations_booking_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['listing_id'], ['channel_listings.id'], name=op.f('fk_channel_reservations_listing_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_channel_reservations_organisation_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_channel_reservations'))
    )
    op.create_index('ix_channel_reservations_booking', 'channel_reservations', ['booking_id'], unique=False)
    op.create_index(op.f('ix_channel_reservations_organisation_id'), 'channel_reservations', ['organisation_id'], unique=False)
    op.create_index('uq_channel_reservations_listing_id_external_reservation_id', 'channel_reservations', ['listing_id', 'external_reservation_id'], unique=True)
    op.create_table('channel_sync_logs',
    sa.Column('connection_id', app.models.base.GUID(length=16), nullable=True),
    sa.Column('listing_id', app.models.base.GUID(length=16), nullable=True),
    sa.Column('condo_label', sa.String(length=255), nullable=True),
    sa.Column('sync_type', sa.Enum('availability', 'reservation', 'pricing', name='synctype', native_enum=False, length=20), nullable=False),
    sa.Column('direction', sa.Enum('inbound', 'outbound', name='syncdirection', native_enum=False, length=16), nullable=False),
    sa.Column('status', sa.Enum('success', 'failed', 'skipped', name='syncstatus', native_enum=False, length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('reference', sa.String(length=128), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('items_created', sa.Integer(), nullable=False),
    sa.Column('items_updated', sa.Integer(), nullable=False),
    sa.Column('items_cancelled', sa.Integer(), nullable=False),
    sa.Column('items_skipped', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('id', app.models.base.GUID(length=16), nullable=False),
    sa.Column('organisation_id', app.models.base.GUID(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['channel_connections.id'], name=op.f('fk_channel_sync_logs_connection_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['listing_id'], ['channel_listings.id'], name=op.f('fk_channel_sync_logs_listing_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_channel_sync_logs_organisation_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_channel_sync_logs'))
    )
    op.create_index('ix_channel_sync_logs_listing_created', 'channel_sync_logs', ['listing_id', 'created_at'], unique=False)
    op.create_index('ix_channel_sync_logs_org_created', 'channel_sync_logs', ['organisation_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_channel_sync_logs_organisation_id'), 'channel_sync_logs', ['organisation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # Just the tables. Dropping their indexes first, as autogenerate wrote it,
    # fails on MySQL: once ix_channel_sync_logs_organisation_id is gone the
    # foreign key on that column is held up by the composite index, and
    # dropping that one too raises errno 1553. DROP TABLE removes indexes and
    # foreign keys together and cannot get stuck half-way.
    #
    # Children before parents: sync_logs and reservations both point at
    # listings, and listings points at connections.
    op.drop_table("channel_sync_logs")
    op.drop_table("channel_reservations")
    op.drop_table("channel_listings")
    op.drop_table("channel_connections")
