"""initial schema

Revision ID: 79b0753113e0
Revises: 
Create Date: 2026-08-06 21:29:53.169304
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Binds `app` in this namespace so autogenerate's `app.models.base.GUID(...)`
# references resolve. `import ... as x` would bind only `x`.
import app.models.base  # noqa: F401

revision: str = '79b0753113e0'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_logs',
    sa.Column('actor_id', app.models.base.GUID(length=16), nullable=True),
    sa.Column('actor_name', sa.String(length=160), nullable=True),
    sa.Column('action', sa.Enum('created', 'updated', 'deleted', 'restored', 'logged_in', 'logged_out', 'login_failed', 'uploaded', 'exported', name='activityaction', native_enum=False, length=24), nullable=False),
    sa.Column('entity_type', sa.Enum('user', 'condo', 'booking', 'expense', 'session', name='activityentity', native_enum=False, length=24), nullable=False),
    sa.Column('entity_id', app.models.base.GUID(length=16), nullable=True),
    sa.Column('entity_label', sa.String(length=255), nullable=True),
    sa.Column('meta_json', sa.Text(), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('id', app.models.base.GUID(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_logs'))
    )
    op.create_index('ix_activity_logs_actor', 'activity_logs', ['actor_id'], unique=False)
    op.create_index('ix_activity_logs_created_at', 'activity_logs', ['created_at'], unique=False)
    op.create_index('ix_activity_logs_entity', 'activity_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_table('condos',
    sa.Column('code', sa.String(length=24), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('property_type', sa.Enum('Condominium', 'Serviced apartment', 'Townhouse', name='propertytype', native_enum=False, length=32), nullable=False),
    sa.Column('bedrooms', sa.Integer(), nullable=False),
    sa.Column('bathrooms', sa.Integer(), nullable=False),
    sa.Column('size_sqm', sa.Integer(), nullable=True),
    sa.Column('night_rate', sa.BigInteger(), nullable=False),
    sa.Column('month_rate', sa.BigInteger(), nullable=False),
    sa.Column('cleaning_fee', sa.BigInteger(), nullable=False),
    sa.Column('security_deposit', sa.BigInteger(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_maintenance', sa.Boolean(), nullable=False),
    sa.Column('id', app.models.base.GUID(length=16), nullable=False),
    sa.Column('created_by', app.models.base.GUID(length=16), nullable=True),
    sa.Column('updated_by', app.models.base.GUID(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_condos_created_by'), ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_condos_updated_by'), ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_condos'))
    )
    op.create_index('ix_condos_code', 'condos', ['code'], unique=False)
    op.create_index('ix_condos_deleted_name', 'condos', ['deleted_at', 'name'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('role', sa.Enum('admin', 'staff', 'cleaner', 'accountant', name='role', native_enum=False, length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('id', app.models.base.GUID(length=16), nullable=False),
    sa.Column('created_by', app.models.base.GUID(length=16), nullable=True),
    sa.Column('updated_by', app.models.base.GUID(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_users_created_by'), ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_users_updated_by'), ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index('ix_users_deleted_at', 'users', ['deleted_at'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_index('ix_users_role_active', 'users', ['role', 'is_active'], unique=False)
    op.create_table('condo_images',
    sa.Column('condo_id', app.models.base.GUID(length=16), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('content_type', sa.String(length=64), nullable=False),
    sa.Column('byte_size', sa.BigInteger(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', app.models.base.GUID(length=16), nullable=False),
    sa.Column('created_by', app.models.base.GUID(length=16), nullable=True),
    sa.Column('updated_by', app.models.base.GUID(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['condo_id'], ['condos.id'], name=op.f('fk_condo_images_condo_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_condo_images_created_by'), ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_condo_images_updated_by'), ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_condo_images'))
    )
    op.create_index('ix_condo_images_condo_position', 'condo_images', ['condo_id', 'position'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('user_id', app.models.base.GUID(length=16), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('family_id', app.models.base.GUID(length=16), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('rotated_to', app.models.base.GUID(length=16), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('id', app.models.base.GUID(length=16), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens'))
    )
    op.create_index('ix_refresh_tokens_family_id', 'refresh_tokens', ['family_id'], unique=False)
    op.create_index('ix_refresh_tokens_user_expires', 'refresh_tokens', ['user_id', 'expires_at'], unique=False)
    op.create_index('uq_refresh_tokens_token_hash', 'refresh_tokens', ['token_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_refresh_tokens_token_hash', table_name='refresh_tokens')
    op.drop_index('ix_refresh_tokens_user_expires', table_name='refresh_tokens')
    op.drop_index('ix_refresh_tokens_family_id', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('ix_condo_images_condo_position', table_name='condo_images')
    op.drop_table('condo_images')
    op.drop_index('ix_users_role_active', table_name='users')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_deleted_at', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_condos_deleted_name', table_name='condos')
    op.drop_index('ix_condos_code', table_name='condos')
    op.drop_table('condos')
    op.drop_index('ix_activity_logs_entity', table_name='activity_logs')
    op.drop_index('ix_activity_logs_created_at', table_name='activity_logs')
    op.drop_index('ix_activity_logs_actor', table_name='activity_logs')
    op.drop_table('activity_logs')
    # ### end Alembic commands ###
