"""expenses, categories and payment methods

Revision ID: 977d7dcfbaa3
Revises: c9d22c268816
Create Date: 2026-08-07 10:47:57.634117
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Binds `app` in this namespace so autogenerate's `app.models.base.GUID(...)`
# references resolve. `import ... as x` would bind only `x`.
import app.models.base  # noqa: F401

revision: str = '977d7dcfbaa3'
down_revision: str | None = 'c9d22c268816'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expense_categories',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('tone', sa.String(length=16), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', app.models.base.GUID(length=16), nullable=False),
    sa.Column('created_by', app.models.base.GUID(length=16), nullable=True),
    sa.Column('updated_by', app.models.base.GUID(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_expense_categories_created_by'), ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_expense_categories_updated_by'), ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_expense_categories'))
    )
    op.create_index('uq_expense_categories_name', 'expense_categories', ['name'], unique=True)
    op.create_table('payment_methods',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', app.models.base.GUID(length=16), nullable=False),
    sa.Column('created_by', app.models.base.GUID(length=16), nullable=True),
    sa.Column('updated_by', app.models.base.GUID(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_payment_methods_created_by'), ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_payment_methods_updated_by'), ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_methods'))
    )
    op.create_index('uq_payment_methods_name', 'payment_methods', ['name'], unique=True)
    op.create_table('expenses',
    sa.Column('condo_id', app.models.base.GUID(length=16), nullable=False),
    sa.Column('category_id', app.models.base.GUID(length=16), nullable=False),
    sa.Column('method_id', app.models.base.GUID(length=16), nullable=False),
    sa.Column('spent_on', sa.Date(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('vendor', sa.String(length=160), nullable=True),
    sa.Column('reference', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('paid', 'pending', 'cancelled', name='expensestatus', native_enum=False, length=16), nullable=False),
    sa.Column('receipt_key', sa.String(length=512), nullable=True),
    sa.Column('receipt_filename', sa.String(length=255), nullable=True),
    sa.Column('receipt_content_type', sa.String(length=64), nullable=True),
    sa.Column('receipt_byte_size', sa.BigInteger(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', app.models.base.GUID(length=16), nullable=False),
    sa.Column('created_by', app.models.base.GUID(length=16), nullable=True),
    sa.Column('updated_by', app.models.base.GUID(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['expense_categories.id'], name=op.f('fk_expenses_category_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['condo_id'], ['condos.id'], name=op.f('fk_expenses_condo_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_expenses_created_by'), ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['method_id'], ['payment_methods.id'], name=op.f('fk_expenses_method_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_expenses_updated_by'), ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_expenses'))
    )
    op.create_index('ix_expenses_category', 'expenses', ['category_id'], unique=False)
    op.create_index('ix_expenses_condo_date', 'expenses', ['condo_id', 'spent_on'], unique=False)
    op.create_index('ix_expenses_deleted_status', 'expenses', ['deleted_at', 'status'], unique=False)
    op.create_index('ix_expenses_spent_on', 'expenses', ['spent_on'], unique=False)
    op.create_foreign_key(op.f('fk_bookings_created_by'), 'bookings', 'users', ['created_by'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_bookings_updated_by'), 'bookings', 'users', ['updated_by'], ['id'], ondelete='SET NULL', use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_bookings_updated_by'), 'bookings', type_='foreignkey')
    op.drop_constraint(op.f('fk_bookings_created_by'), 'bookings', type_='foreignkey')
    op.drop_index('ix_expenses_spent_on', table_name='expenses')
    op.drop_index('ix_expenses_deleted_status', table_name='expenses')
    op.drop_index('ix_expenses_condo_date', table_name='expenses')
    op.drop_index('ix_expenses_category', table_name='expenses')
    op.drop_table('expenses')
    op.drop_index('uq_payment_methods_name', table_name='payment_methods')
    op.drop_table('payment_methods')
    op.drop_index('uq_expense_categories_name', table_name='expense_categories')
    op.drop_table('expense_categories')
    # ### end Alembic commands ###
