"""bookings and booking_nights

Revision ID: c9d22c268816
Revises: 79b0753113e0
Create Date: 2026-08-07 09:26:09.155466
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Binds `app` in this namespace so autogenerate's `app.models.base.GUID(...)`
# references resolve. `import ... as x` would bind only `x`.
import app.models.base  # noqa: F401

revision: str = 'c9d22c268816'
down_revision: str | None = '79b0753113e0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('condo_id', app.models.base.GUID(length=16), nullable=False),
    sa.Column('guest_name', sa.String(length=160), nullable=False),
    sa.Column('guest_phone', sa.String(length=40), nullable=True),
    sa.Column('guest_email', sa.String(length=255), nullable=True),
    sa.Column('check_in', sa.Date(), nullable=False),
    sa.Column('check_out', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('booked', 'pending', 'maintenance', 'cancelled', name='bookingstatus', native_enum=False, length=20), nullable=False),
    sa.Column('pricing_mode', sa.Enum('nightly', 'total', name='pricingmodecolumn', native_enum=False, length=16), nullable=False),
    sa.Column('night_rate', sa.BigInteger(), nullable=False),
    sa.Column('subtotal', sa.BigInteger(), nullable=False),
    sa.Column('discount', sa.BigInteger(), nullable=False),
    sa.Column('cleaning_fee', sa.BigInteger(), nullable=False),
    sa.Column('other_charges', sa.BigInteger(), nullable=False),
    sa.Column('tax_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tax', sa.BigInteger(), nullable=False),
    sa.Column('total', sa.BigInteger(), nullable=False),
    sa.Column('received', sa.BigInteger(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', app.models.base.GUID(length=16), nullable=False),
    sa.Column('created_by', app.models.base.GUID(length=16), nullable=True),
    sa.Column('updated_by', app.models.base.GUID(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['condo_id'], ['condos.id'], name=op.f('fk_bookings_condo_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_bookings_created_by'), ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_bookings_updated_by'), ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bookings'))
    )
    op.create_index('ix_bookings_check_in', 'bookings', ['check_in'], unique=False)
    op.create_index('ix_bookings_condo_dates', 'bookings', ['condo_id', 'check_in', 'check_out'], unique=False)
    op.create_index('ix_bookings_deleted_status', 'bookings', ['deleted_at', 'status'], unique=False)
    op.create_index('ix_bookings_guest_name', 'bookings', ['guest_name'], unique=False)
    op.create_table('booking_nights',
    sa.Column('condo_id', app.models.base.GUID(length=16), nullable=False),
    sa.Column('night_date', sa.Date(), nullable=False),
    sa.Column('booking_id', app.models.base.GUID(length=16), nullable=False),
    sa.Column('revenue_share', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_booking_nights_booking_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['condo_id'], ['condos.id'], name=op.f('fk_booking_nights_condo_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('condo_id', 'night_date', name=op.f('pk_booking_nights'))
    )
    op.create_index('ix_booking_nights_booking', 'booking_nights', ['booking_id'], unique=False)
    op.create_index('ix_booking_nights_date', 'booking_nights', ['night_date'], unique=False)
    op.create_foreign_key(op.f('fk_condo_images_created_by'), 'condo_images', 'users', ['created_by'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_condo_images_updated_by'), 'condo_images', 'users', ['updated_by'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_condos_created_by'), 'condos', 'users', ['created_by'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_condos_updated_by'), 'condos', 'users', ['updated_by'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_users_created_by'), 'users', 'users', ['created_by'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_users_updated_by'), 'users', 'users', ['updated_by'], ['id'], ondelete='SET NULL', use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_users_updated_by'), 'users', type_='foreignkey')
    op.drop_constraint(op.f('fk_users_created_by'), 'users', type_='foreignkey')
    op.drop_constraint(op.f('fk_condos_updated_by'), 'condos', type_='foreignkey')
    op.drop_constraint(op.f('fk_condos_created_by'), 'condos', type_='foreignkey')
    op.drop_constraint(op.f('fk_condo_images_updated_by'), 'condo_images', type_='foreignkey')
    op.drop_constraint(op.f('fk_condo_images_created_by'), 'condo_images', type_='foreignkey')
    op.drop_index('ix_booking_nights_date', table_name='booking_nights')
    op.drop_index('ix_booking_nights_booking', table_name='booking_nights')
    op.drop_table('booking_nights')
    op.drop_index('ix_bookings_guest_name', table_name='bookings')
    op.drop_index('ix_bookings_deleted_status', table_name='bookings')
    op.drop_index('ix_bookings_condo_dates', table_name='bookings')
    op.drop_index('ix_bookings_check_in', table_name='bookings')
    op.drop_table('bookings')
    # ### end Alembic commands ###
